// <auto-generated />
using CMLearningWords.AccessToData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMLearningWords.AccessToData.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20180728213109_FirsPushDataBase")]
    partial class FirsPushDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMLearningWords.DataModels.Models.StageOfMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("StageOfMethods");
                });

            modelBuilder.Entity("CMLearningWords.DataModels.Models.TranslationOfWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ExeptionInWord");

                    b.Property<bool>("MustBeRemove");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RightTranslation")
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("WordInEnglishId");

                    b.HasKey("Id");

                    b.HasIndex("WordInEnglishId");

                    b.ToTable("TranslationOfWords");
                });

            modelBuilder.Entity("CMLearningWords.DataModels.Models.WordInEnglish", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ExeptionInWord");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RightWord")
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("StageOfMethodId");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StageOfMethodId");

                    b.ToTable("WordsInEnglish");
                });

            modelBuilder.Entity("CMLearningWords.DataModels.Models.TranslationOfWord", b =>
                {
                    b.HasOne("CMLearningWords.DataModels.Models.WordInEnglish", "WordInEnglish")
                        .WithMany("TranslationOfWords")
                        .HasForeignKey("WordInEnglishId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CMLearningWords.DataModels.Models.WordInEnglish", b =>
                {
                    b.HasOne("CMLearningWords.DataModels.Models.StageOfMethod", "StageOfMethod")
                        .WithMany()
                        .HasForeignKey("StageOfMethodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
